import { MigrationInterface, QueryRunner } from "typeorm";

export class AddSmsNotificationBatchFields1743800379261 implements MigrationInterface {
    name = 'AddSmsNotificationBatchFields1743800379261'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`accounts\` DROP FOREIGN KEY \`accounts_ibfk_1\``);
        await queryRunner.query(`ALTER TABLE \`sms_templates\` DROP FOREIGN KEY \`sms_templates_ibfk_1\``);
        await queryRunner.query(`ALTER TABLE \`sms_received_messages\` DROP FOREIGN KEY \`sms_received_messages_ibfk_1\``);
        await queryRunner.query(`ALTER TABLE \`sms_messages\` DROP FOREIGN KEY \`sms_messages_ibfk_1\``);
        await queryRunner.query(`ALTER TABLE \`sms_messages\` DROP FOREIGN KEY \`sms_messages_ibfk_2\``);
        await queryRunner.query(`ALTER TABLE \`sms_dispatch_batches\` DROP FOREIGN KEY \`sms_dispatch_batches_ibfk_1\``);
        await queryRunner.query(`ALTER TABLE \`sms_dispatch_batches\` DROP FOREIGN KEY \`sms_dispatch_batches_ibfk_2\``);
        await queryRunner.query(`ALTER TABLE \`payments\` DROP FOREIGN KEY \`payments_ibfk_1\``);
        await queryRunner.query(`ALTER TABLE \`email_templates\` DROP FOREIGN KEY \`email_templates_ibfk_1\``);
        await queryRunner.query(`ALTER TABLE \`email_messages\` DROP FOREIGN KEY \`email_messages_ibfk_1\``);
        await queryRunner.query(`ALTER TABLE \`email_notification_batches\` DROP FOREIGN KEY \`email_notification_batches_ibfk_1\``);
        await queryRunner.query(`ALTER TABLE \`email_notification_batches\` DROP FOREIGN KEY \`email_notification_batches_ibfk_2\``);
        await queryRunner.query(`DROP INDEX \`user_id\` ON \`accounts\``);
        await queryRunner.query(`DROP INDEX \`email\` ON \`users\``);
        await queryRunner.query(`DROP INDEX \`username\` ON \`users\``);
        await queryRunner.query(`DROP INDEX \`idx_sms_templates_user_id\` ON \`sms_templates\``);
        await queryRunner.query(`DROP INDEX \`name\` ON \`sms_providers\``);
        await queryRunner.query(`DROP INDEX \`idx_sms_received_at\` ON \`sms_received_messages\``);
        await queryRunner.query(`DROP INDEX \`idx_sms_received_recipient\` ON \`sms_received_messages\``);
        await queryRunner.query(`DROP INDEX \`idx_sms_received_sender\` ON \`sms_received_messages\``);
        await queryRunner.query(`DROP INDEX \`provider_message_id\` ON \`sms_received_messages\``);
        await queryRunner.query(`DROP INDEX \`sms_provider_id\` ON \`sms_received_messages\``);
        await queryRunner.query(`DROP INDEX \`idx_sm_dispatch_batch_id\` ON \`sms_messages\``);
        await queryRunner.query(`DROP INDEX \`idx_sm_provider_id_status\` ON \`sms_messages\``);
        await queryRunner.query(`DROP INDEX \`idx_sm_provider_msgid\` ON \`sms_messages\``);
        await queryRunner.query(`DROP INDEX \`idx_sm_recipient_number\` ON \`sms_messages\``);
        await queryRunner.query(`DROP INDEX \`idx_sm_status\` ON \`sms_messages\``);
        await queryRunner.query(`DROP INDEX \`uk_sm_provider_msgid\` ON \`sms_messages\``);
        await queryRunner.query(`DROP INDEX \`idx_sdb_status\` ON \`sms_dispatch_batches\``);
        await queryRunner.query(`DROP INDEX \`idx_sdb_user_id\` ON \`sms_dispatch_batches\``);
        await queryRunner.query(`DROP INDEX \`request_id\` ON \`sms_dispatch_batches\``);
        await queryRunner.query(`DROP INDEX \`template_id\` ON \`sms_dispatch_batches\``);
        await queryRunner.query(`DROP INDEX \`idx_payments_status\` ON \`payments\``);
        await queryRunner.query(`DROP INDEX \`idx_payments_user_id\` ON \`payments\``);
        await queryRunner.query(`DROP INDEX \`transaction_id\` ON \`payments\``);
        await queryRunner.query(`DROP INDEX \`idx_email_templates_user_id\` ON \`email_templates\``);
        await queryRunner.query(`DROP INDEX \`idx_email_received_at\` ON \`email_received_messages\``);
        await queryRunner.query(`DROP INDEX \`idx_email_received_recipient\` ON \`email_received_messages\``);
        await queryRunner.query(`DROP INDEX \`idx_email_received_sender\` ON \`email_received_messages\``);
        await queryRunner.query(`DROP INDEX \`idx_email_received_type\` ON \`email_received_messages\``);
        await queryRunner.query(`DROP INDEX \`message_id_header\` ON \`email_received_messages\``);
        await queryRunner.query(`DROP INDEX \`idx_email_messages_batch_id\` ON \`email_messages\``);
        await queryRunner.query(`DROP INDEX \`idx_email_messages_status\` ON \`email_messages\``);
        await queryRunner.query(`DROP INDEX \`provider_message_id\` ON \`email_messages\``);
        await queryRunner.query(`DROP INDEX \`idx_email_batches_status\` ON \`email_notification_batches\``);
        await queryRunner.query(`DROP INDEX \`idx_email_batches_user_id\` ON \`email_notification_batches\``);
        await queryRunner.query(`ALTER TABLE \`accounts\` COMMENT ''`);
        await queryRunner.query(`ALTER TABLE \`users\` COMMENT ''`);
        await queryRunner.query(`ALTER TABLE \`sms_templates\` COMMENT ''`);
        await queryRunner.query(`ALTER TABLE \`sms_providers\` COMMENT ''`);
        await queryRunner.query(`ALTER TABLE \`sms_received_messages\` COMMENT ''`);
        await queryRunner.query(`ALTER TABLE \`sms_messages\` COMMENT ''`);
        await queryRunner.query(`ALTER TABLE \`sms_dispatch_batches\` COMMENT ''`);
        await queryRunner.query(`ALTER TABLE \`sms_dispatch_batches\` COMMENT ''`);
        await queryRunner.query(`ALTER TABLE \`sms_messages\` COMMENT ''`);
        await queryRunner.query(`ALTER TABLE \`payments\` COMMENT ''`);
        await queryRunner.query(`ALTER TABLE \`email_templates\` COMMENT ''`);
        await queryRunner.query(`ALTER TABLE \`email_received_messages\` COMMENT ''`);
        await queryRunner.query(`ALTER TABLE \`email_messages\` COMMENT ''`);
        await queryRunner.query(`ALTER TABLE \`email_notification_batches\` COMMENT ''`);
        await queryRunner.query(`ALTER TABLE \`sms_dispatch_batches\` ADD \`content_type\` enum ('template', 'direct') NULL COMMENT '内容类型：模板或直接内容' DEFAULT 'template'`);
        await queryRunner.query(`ALTER TABLE \`sms_dispatch_batches\` ADD \`direct_content\` text NULL COMMENT '直接发送的内容（如果不使用模板）'`);
        await queryRunner.query(`ALTER TABLE \`sms_dispatch_batches\` ADD \`processed_count\` int UNSIGNED NULL COMMENT '已处理的消息数量'`);
        await queryRunner.query(`ALTER TABLE \`sms_dispatch_batches\` ADD \`success_count\` int UNSIGNED NULL COMMENT '成功发送的消息数量'`);
        await queryRunner.query(`ALTER TABLE \`sms_dispatch_batches\` ADD \`failure_count\` int UNSIGNED NULL COMMENT '发送失败的消息数量'`);
        await queryRunner.query(`ALTER TABLE \`sms_dispatch_batches\` ADD \`processing_completed_at\` timestamp NULL COMMENT '处理完成时间'`);
        await queryRunner.query(`ALTER TABLE \`accounts\` DROP FOREIGN KEY \`FK_3000dad1da61b29953f07476324\``);
        await queryRunner.query(`ALTER TABLE \`accounts\` CHANGE \`id\` \`id\` int NOT NULL AUTO_INCREMENT`);
        await queryRunner.query(`ALTER TABLE \`accounts\` CHANGE \`user_id\` \`user_id\` int UNSIGNED NOT NULL COMMENT '用户ID'`);
        await queryRunner.query(`ALTER TABLE \`accounts\` ADD UNIQUE INDEX \`IDX_3000dad1da61b29953f0747632\` (\`user_id\`)`);
        await queryRunner.query(`ALTER TABLE \`accounts\` CHANGE \`balance\` \`balance\` decimal(12,4) NOT NULL COMMENT '账户余额' DEFAULT '0.0000'`);
        await queryRunner.query(`ALTER TABLE \`accounts\` CHANGE \`created_at\` \`created_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`accounts\` CHANGE \`updated_at\` \`updated_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`username\` \`username\` varchar(100) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD UNIQUE INDEX \`IDX_fe0bb3f6520ee0469504521e71\` (\`username\`)`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`password_hash\` \`password_hash\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`email\` \`email\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD UNIQUE INDEX \`IDX_97672ac88f789774dd47f7c8be\` (\`email\`)`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`role\` \`role\` enum ('admin', 'user') NOT NULL DEFAULT 'user'`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`is_active\` \`is_active\` tinyint NOT NULL DEFAULT 1`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`created_at\` \`created_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`updated_at\` \`updated_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`sms_templates\` CHANGE \`user_id\` \`user_id\` int UNSIGNED NOT NULL COMMENT '创建模板的用户ID'`);
        await queryRunner.query(`ALTER TABLE \`sms_templates\` DROP COLUMN \`name\``);
        await queryRunner.query(`ALTER TABLE \`sms_templates\` ADD \`name\` varchar(100) NOT NULL COMMENT '模板名称'`);
        await queryRunner.query(`ALTER TABLE \`sms_templates\` ADD UNIQUE INDEX \`IDX_d9bd873bf52604c57cdcec10b4\` (\`name\`)`);
        await queryRunner.query(`ALTER TABLE \`sms_templates\` CHANGE \`content\` \`content\` text NOT NULL COMMENT '模板内容'`);
        await queryRunner.query(`ALTER TABLE \`sms_templates\` DROP COLUMN \`provider_template_id\``);
        await queryRunner.query(`ALTER TABLE \`sms_templates\` ADD \`provider_template_id\` varchar(255) NULL COMMENT '服务商处的模板ID (如果需要在服务商预注册)'`);
        await queryRunner.query(`ALTER TABLE \`sms_templates\` CHANGE \`variables\` \`variables\` json NULL COMMENT '模板变量列表'`);
        await queryRunner.query(`ALTER TABLE \`sms_templates\` CHANGE \`created_at\` \`created_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`sms_templates\` CHANGE \`updated_at\` \`updated_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`sms_providers\` CHANGE \`name\` \`name\` varchar(100) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`sms_providers\` ADD UNIQUE INDEX \`IDX_543d375bc13c040df4c53f23ac\` (\`name\`)`);
        await queryRunner.query(`ALTER TABLE \`sms_providers\` CHANGE \`display_name\` \`display_name\` varchar(150) NULL`);
        await queryRunner.query(`ALTER TABLE \`sms_providers\` CHANGE \`api_key\` \`api_key\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`sms_providers\` CHANGE \`api_secret\` \`api_secret\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`sms_providers\` CHANGE \`base_url\` \`base_url\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`sms_providers\` CHANGE \`config_details\` \`config_details\` json NULL`);
        await queryRunner.query(`ALTER TABLE \`sms_providers\` CHANGE \`is_active\` \`is_active\` tinyint NOT NULL DEFAULT 1`);
        await queryRunner.query(`ALTER TABLE \`sms_providers\` CHANGE \`created_at\` \`created_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`sms_providers\` CHANGE \`updated_at\` \`updated_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`sms_received_messages\` CHANGE \`sms_provider_id\` \`sms_provider_id\` int UNSIGNED NOT NULL COMMENT '接收消息的服务商ID'`);
        await queryRunner.query(`ALTER TABLE \`sms_received_messages\` CHANGE \`provider_message_id\` \`provider_message_id\` varchar(255) NULL COMMENT '服务商侧的消息唯一ID'`);
        await queryRunner.query(`ALTER TABLE \`sms_received_messages\` ADD UNIQUE INDEX \`IDX_66be7944e1306a00f04c8951b6\` (\`provider_message_id\`)`);
        await queryRunner.query(`ALTER TABLE \`sms_received_messages\` CHANGE \`sender_number\` \`sender_number\` varchar(50) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`sms_received_messages\` CHANGE \`recipient_number\` \`recipient_number\` varchar(50) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`sms_received_messages\` CHANGE \`content\` \`content\` text NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`sms_received_messages\` CHANGE \`received_at\` \`received_at\` timestamp NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`sms_received_messages\` CHANGE \`created_at\` \`created_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`sms_messages\` CHANGE \`id\` \`id\` bigint UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '系统内部唯一消息ID'`);
        await queryRunner.query(`ALTER TABLE \`sms_messages\` CHANGE \`dispatch_batch_id\` \`dispatch_batch_id\` bigint UNSIGNED NOT NULL COMMENT '关联的用户请求批次ID'`);
        await queryRunner.query(`ALTER TABLE \`sms_messages\` CHANGE \`provider_id\` \`provider_id\` int UNSIGNED NOT NULL COMMENT '最终选择的短信服务商ID'`);
        await queryRunner.query(`ALTER TABLE \`sms_messages\` CHANGE \`recipient_number\` \`recipient_number\` varchar(50) NOT NULL COMMENT '接收者手机号'`);
        await queryRunner.query(`ALTER TABLE \`sms_messages\` CHANGE \`status\` \`status\` enum ('pending', 'queued', 'submitted', 'sent', 'delivered', 'failed', 'rejected', 'unknown') NOT NULL COMMENT '标准化的短信状态' DEFAULT 'pending'`);
        await queryRunner.query(`ALTER TABLE \`sms_messages\` CHANGE \`provider_msgid\` \`provider_msgid\` varchar(255) NULL COMMENT '服务商返回的消息ID'`);
        await queryRunner.query(`ALTER TABLE \`sms_messages\` ADD UNIQUE INDEX \`IDX_1c352885b3a00833386c570d2b\` (\`provider_msgid\`)`);
        await queryRunner.query(`ALTER TABLE \`sms_messages\` CHANGE \`provider_orderid\` \`provider_orderid\` varchar(255) NULL COMMENT '发送时传递给服务商的自定义ID'`);
        await queryRunner.query(`ALTER TABLE \`sms_messages\` CHANGE \`provider_status_code\` \`provider_status_code\` varchar(100) NULL COMMENT '服务商返回的原始状态码或描述'`);
        await queryRunner.query(`ALTER TABLE \`sms_messages\` CHANGE \`error_message\` \`error_message\` text NULL COMMENT '错误信息描述'`);
        await queryRunner.query(`ALTER TABLE \`sms_messages\` CHANGE \`submitted_at\` \`submitted_at\` timestamp NULL COMMENT '成功提交给服务商的时间'`);
        await queryRunner.query(`ALTER TABLE \`sms_messages\` CHANGE \`provider_reported_at\` \`provider_reported_at\` timestamp NULL COMMENT '服务商报告的发送/送达时间'`);
        await queryRunner.query(`ALTER TABLE \`sms_messages\` CHANGE \`last_status_check_at\` \`last_status_check_at\` timestamp NULL COMMENT '最后一次主动查询状态的时间'`);
        await queryRunner.query(`ALTER TABLE \`sms_messages\` CHANGE \`created_at\` \`created_at\` timestamp(6) NOT NULL COMMENT '记录创建时间' DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`sms_messages\` CHANGE \`updated_at\` \`updated_at\` timestamp(6) NOT NULL COMMENT '记录更新时间' DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`sms_dispatch_batches\` CHANGE \`user_id\` \`user_id\` int UNSIGNED NOT NULL COMMENT '发起请求的用户ID'`);
        await queryRunner.query(`ALTER TABLE \`sms_dispatch_batches\` CHANGE \`request_id\` \`request_id\` varchar(64) NULL`);
        await queryRunner.query(`ALTER TABLE \`sms_dispatch_batches\` ADD UNIQUE INDEX \`IDX_39a1276cb4b18c33358ead18aa\` (\`request_id\`)`);
        await queryRunner.query(`ALTER TABLE \`sms_dispatch_batches\` CHANGE \`status\` \`status\` enum ('pending', 'processing', 'partially_completed', 'completed', 'failed') NOT NULL COMMENT '批次整体处理状态' DEFAULT 'pending'`);
        await queryRunner.query(`ALTER TABLE \`sms_dispatch_batches\` CHANGE \`template_id\` \`template_id\` int UNSIGNED NULL COMMENT '使用的短信模板ID'`);
        await queryRunner.query(`ALTER TABLE \`sms_dispatch_batches\` CHANGE \`content\` \`content\` text NOT NULL COMMENT '要发送的短信内容'`);
        await queryRunner.query(`ALTER TABLE \`sms_dispatch_batches\` CHANGE \`recipients\` \`recipients\` json NOT NULL COMMENT '用户请求的接收者号码列表'`);
        await queryRunner.query(`ALTER TABLE \`sms_dispatch_batches\` CHANGE \`recipient_count\` \`recipient_count\` int UNSIGNED NOT NULL COMMENT '请求中的接收者数量'`);
        await queryRunner.query(`ALTER TABLE \`sms_dispatch_batches\` CHANGE \`scheduled_at\` \`scheduled_at\` timestamp NULL COMMENT '预定发送时间'`);
        await queryRunner.query(`ALTER TABLE \`sms_dispatch_batches\` CHANGE \`processing_started_at\` \`processing_started_at\` timestamp NULL COMMENT '开始处理时间'`);
        await queryRunner.query(`ALTER TABLE \`sms_dispatch_batches\` CHANGE \`completed_at\` \`completed_at\` timestamp NULL COMMENT '批次完成处理时间'`);
        await queryRunner.query(`ALTER TABLE \`sms_dispatch_batches\` CHANGE \`created_at\` \`created_at\` timestamp(6) NOT NULL COMMENT '创建时间' DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`sms_dispatch_batches\` CHANGE \`updated_at\` \`updated_at\` timestamp(6) NOT NULL COMMENT '更新时间' DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`sms_dispatch_batches\` CHANGE \`user_id\` \`user_id\` int UNSIGNED NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`sms_dispatch_batches\` CHANGE \`request_id\` \`request_id\` varchar(64) NULL`);
        await queryRunner.query(`ALTER TABLE \`sms_dispatch_batches\` ADD UNIQUE INDEX \`IDX_39a1276cb4b18c33358ead18aa\` (\`request_id\`)`);
        await queryRunner.query(`ALTER TABLE \`sms_dispatch_batches\` CHANGE \`template_id\` \`template_id\` int UNSIGNED NULL`);
        await queryRunner.query(`ALTER TABLE \`sms_dispatch_batches\` CHANGE \`content\` \`content\` text NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`sms_dispatch_batches\` CHANGE \`recipients\` \`recipients\` json NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`sms_dispatch_batches\` CHANGE \`recipient_count\` \`recipient_count\` int UNSIGNED NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`sms_dispatch_batches\` CHANGE \`status\` \`status\` enum ('pending', 'processing', 'partially_completed', 'completed', 'failed') NOT NULL DEFAULT 'pending'`);
        await queryRunner.query(`ALTER TABLE \`sms_dispatch_batches\` CHANGE \`scheduled_at\` \`scheduled_at\` timestamp NULL`);
        await queryRunner.query(`ALTER TABLE \`sms_dispatch_batches\` CHANGE \`processing_started_at\` \`processing_started_at\` timestamp NULL`);
        await queryRunner.query(`ALTER TABLE \`sms_dispatch_batches\` CHANGE \`completed_at\` \`completed_at\` timestamp NULL`);
        await queryRunner.query(`ALTER TABLE \`sms_dispatch_batches\` CHANGE \`created_at\` \`created_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`sms_dispatch_batches\` CHANGE \`updated_at\` \`updated_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`sms_messages\` CHANGE \`id\` \`id\` bigint UNSIGNED NOT NULL AUTO_INCREMENT`);
        await queryRunner.query(`ALTER TABLE \`sms_messages\` CHANGE \`dispatch_batch_id\` \`dispatch_batch_id\` bigint UNSIGNED NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`sms_messages\` CHANGE \`recipient_number\` \`recipient_number\` varchar(50) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`sms_messages\` CHANGE \`provider_id\` \`provider_id\` int UNSIGNED NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`sms_messages\` CHANGE \`provider_msgid\` \`provider_msgid\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`sms_messages\` CHANGE \`provider_orderid\` \`provider_orderid\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`sms_messages\` CHANGE \`status\` \`status\` enum ('pending', 'queued', 'submitted', 'sent', 'delivered', 'failed', 'rejected', 'unknown') NOT NULL DEFAULT 'pending'`);
        await queryRunner.query(`ALTER TABLE \`sms_messages\` CHANGE \`provider_status_code\` \`provider_status_code\` varchar(100) NULL`);
        await queryRunner.query(`ALTER TABLE \`sms_messages\` CHANGE \`error_message\` \`error_message\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`sms_messages\` CHANGE \`submitted_at\` \`submitted_at\` timestamp NULL`);
        await queryRunner.query(`ALTER TABLE \`sms_messages\` CHANGE \`provider_reported_at\` \`provider_reported_at\` timestamp NULL`);
        await queryRunner.query(`ALTER TABLE \`sms_messages\` CHANGE \`last_status_check_at\` \`last_status_check_at\` timestamp NULL`);
        await queryRunner.query(`ALTER TABLE \`sms_messages\` CHANGE \`created_at\` \`created_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`sms_messages\` CHANGE \`updated_at\` \`updated_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`payments\` DROP FOREIGN KEY \`FK_427785468fb7d2733f59e7d7d39\``);
        await queryRunner.query(`ALTER TABLE \`payments\` CHANGE \`user_id\` \`user_id\` int UNSIGNED NOT NULL COMMENT '关联的用户ID'`);
        await queryRunner.query(`ALTER TABLE \`payments\` CHANGE \`amount\` \`amount\` decimal(10,2) NOT NULL COMMENT '支付金额'`);
        await queryRunner.query(`ALTER TABLE \`payments\` CHANGE \`status\` \`status\` enum ('pending', 'completed', 'failed') NOT NULL COMMENT '支付状态' DEFAULT 'pending'`);
        await queryRunner.query(`ALTER TABLE \`payments\` CHANGE \`transaction_id\` \`transaction_id\` varchar(255) NULL COMMENT '支付网关返回的交易ID'`);
        await queryRunner.query(`ALTER TABLE \`payments\` ADD UNIQUE INDEX \`IDX_3c324ca49dabde7ffc0ef64675\` (\`transaction_id\`)`);
        await queryRunner.query(`ALTER TABLE \`payments\` CHANGE \`payment_method\` \`payment_method\` varchar(50) NULL COMMENT '支付方式 (e.g., alipay, wechat)'`);
        await queryRunner.query(`ALTER TABLE \`payments\` CHANGE \`created_at\` \`created_at\` timestamp(6) NOT NULL COMMENT '创建时间' DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`payments\` CHANGE \`updated_at\` \`updated_at\` timestamp(6) NOT NULL COMMENT '更新时间' DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`email_templates\` DROP FOREIGN KEY \`FK_513421601bd786a33c5a7238f45\``);
        await queryRunner.query(`ALTER TABLE \`email_templates\` CHANGE \`user_id\` \`user_id\` int UNSIGNED NOT NULL COMMENT '创建模板的用户ID'`);
        await queryRunner.query(`ALTER TABLE \`email_templates\` CHANGE \`name\` \`name\` varchar(150) NOT NULL COMMENT '模板名称'`);
        await queryRunner.query(`ALTER TABLE \`email_templates\` CHANGE \`subject\` \`subject\` varchar(255) NOT NULL COMMENT '邮件主题模板'`);
        await queryRunner.query(`ALTER TABLE \`email_templates\` CHANGE \`body_html\` \`body_html\` text NULL COMMENT 'HTML 格式邮件正文模板'`);
        await queryRunner.query(`ALTER TABLE \`email_templates\` CHANGE \`body_text\` \`body_text\` text NULL COMMENT '纯文本格式邮件正文模板'`);
        await queryRunner.query(`ALTER TABLE \`email_templates\` CHANGE \`variables\` \`variables\` json NULL COMMENT '模板中使用的变量列表 (e.g., ["link", "productName"])'`);
        await queryRunner.query(`ALTER TABLE \`email_templates\` CHANGE \`created_at\` \`created_at\` timestamp(6) NOT NULL COMMENT '创建时间' DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`email_templates\` CHANGE \`updated_at\` \`updated_at\` timestamp(6) NOT NULL COMMENT '更新时间' DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`email_received_messages\` CHANGE \`message_id_header\` \`message_id_header\` varchar(255) NULL COMMENT '邮件的 Message-ID header'`);
        await queryRunner.query(`ALTER TABLE \`email_received_messages\` ADD UNIQUE INDEX \`IDX_d4ea1ecd6fed315ed1bdd41bd0\` (\`message_id_header\`)`);
        await queryRunner.query(`ALTER TABLE \`email_received_messages\` CHANGE \`in_reply_to_header\` \`in_reply_to_header\` varchar(255) NULL COMMENT '邮件的 In-Reply-To header'`);
        await queryRunner.query(`ALTER TABLE \`email_received_messages\` CHANGE \`sender_email\` \`sender_email\` varchar(255) NOT NULL COMMENT '发送者邮箱'`);
        await queryRunner.query(`ALTER TABLE \`email_received_messages\` CHANGE \`recipient_email\` \`recipient_email\` varchar(255) NOT NULL COMMENT '接收者邮箱 (本平台邮箱)'`);
        await queryRunner.query(`ALTER TABLE \`email_received_messages\` CHANGE \`subject\` \`subject\` varchar(500) NULL COMMENT '邮件主题'`);
        await queryRunner.query(`ALTER TABLE \`email_received_messages\` CHANGE \`body_html\` \`body_html\` mediumtext NULL COMMENT 'HTML 正文'`);
        await queryRunner.query(`ALTER TABLE \`email_received_messages\` CHANGE \`body_text\` \`body_text\` mediumtext NULL COMMENT '纯文本正文'`);
        await queryRunner.query(`ALTER TABLE \`email_received_messages\` CHANGE \`received_at\` \`received_at\` timestamp NOT NULL COMMENT '接收时间'`);
        await queryRunner.query(`ALTER TABLE \`email_received_messages\` CHANGE \`type\` \`type\` enum ('inbound', 'bounce', 'reply', 'complaint') NOT NULL COMMENT '邮件类型' DEFAULT 'inbound'`);
        await queryRunner.query(`ALTER TABLE \`email_received_messages\` CHANGE \`created_at\` \`created_at\` timestamp(6) NOT NULL COMMENT '记录创建时间' DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`email_messages\` DROP FOREIGN KEY \`FK_71e3eda7c4f6f8aabc04ddf6a54\``);
        await queryRunner.query(`ALTER TABLE \`email_messages\` CHANGE \`batch_id\` \`batch_id\` bigint UNSIGNED NOT NULL COMMENT '所属推送批次ID'`);
        await queryRunner.query(`ALTER TABLE \`email_messages\` CHANGE \`recipient_email\` \`recipient_email\` varchar(255) NOT NULL COMMENT '接收者邮箱地址'`);
        await queryRunner.query(`ALTER TABLE \`email_messages\` CHANGE \`status\` \`status\` varchar(50) NOT NULL COMMENT '发送状态 (e.g., queued, pending, sending, sent, delivered, bounced, failed, rejected)' DEFAULT 'pending'`);
        await queryRunner.query(`ALTER TABLE \`email_messages\` CHANGE \`provider_message_id\` \`provider_message_id\` varchar(255) NULL COMMENT '服务商返回的消息ID'`);
        await queryRunner.query(`ALTER TABLE \`email_messages\` ADD UNIQUE INDEX \`IDX_eabe2566f0aa286b2ccad53896\` (\`provider_message_id\`)`);
        await queryRunner.query(`ALTER TABLE \`email_messages\` CHANGE \`error_message\` \`error_message\` text NULL COMMENT '错误信息描述'`);
        await queryRunner.query(`ALTER TABLE \`email_messages\` CHANGE \`sent_at\` \`sent_at\` timestamp NULL COMMENT '发送时间'`);
        await queryRunner.query(`ALTER TABLE \`email_messages\` CHANGE \`status_updated_at\` \`status_updated_at\` timestamp NULL COMMENT '状态最后更新时间'`);
        await queryRunner.query(`ALTER TABLE \`email_messages\` CHANGE \`created_at\` \`created_at\` timestamp(6) NOT NULL COMMENT '创建时间' DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`email_messages\` CHANGE \`updated_at\` \`updated_at\` timestamp(6) NOT NULL COMMENT '更新时间' DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`email_notification_batches\` DROP FOREIGN KEY \`FK_9f4e430c1c80093618e4ee92f66\``);
        await queryRunner.query(`ALTER TABLE \`email_notification_batches\` DROP FOREIGN KEY \`FK_ac9f76352644690608b020e443c\``);
        await queryRunner.query(`ALTER TABLE \`email_notification_batches\` CHANGE \`user_id\` \`user_id\` int UNSIGNED NOT NULL COMMENT '发起推送的用户ID'`);
        await queryRunner.query(`ALTER TABLE \`email_notification_batches\` CHANGE \`email_template_id\` \`email_template_id\` int UNSIGNED NULL COMMENT '使用的邮件模板ID'`);
        await queryRunner.query(`ALTER TABLE \`email_notification_batches\` CHANGE \`subject\` \`subject\` varchar(255) NULL COMMENT '邮件主题'`);
        await queryRunner.query(`ALTER TABLE \`email_notification_batches\` DROP COLUMN \`body_html\``);
        await queryRunner.query(`ALTER TABLE \`email_notification_batches\` ADD \`body_html\` mediumtext NULL COMMENT 'HTML邮件正文'`);
        await queryRunner.query(`ALTER TABLE \`email_notification_batches\` CHANGE \`body_text\` \`body_text\` text NULL COMMENT '纯文本邮件正文'`);
        await queryRunner.query(`ALTER TABLE \`email_notification_batches\` CHANGE \`total_recipients\` \`total_recipients\` int UNSIGNED NOT NULL COMMENT '总接收邮箱数量'`);
        await queryRunner.query(`ALTER TABLE \`email_notification_batches\` CHANGE \`processed_count\` \`processed_count\` int UNSIGNED NOT NULL COMMENT '已处理数量' DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE \`email_notification_batches\` CHANGE \`sent_count\` \`sent_count\` int UNSIGNED NOT NULL COMMENT '成功发送数量' DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE \`email_notification_batches\` CHANGE \`failed_count\` \`failed_count\` int UNSIGNED NOT NULL COMMENT '发送失败数量' DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE \`email_notification_batches\` CHANGE \`status\` \`status\` enum ('pending', 'processing', 'partially_completed', 'completed', 'failed') NOT NULL COMMENT '批次状态' DEFAULT 'pending'`);
        await queryRunner.query(`ALTER TABLE \`email_notification_batches\` CHANGE \`scheduled_at\` \`scheduled_at\` timestamp NULL COMMENT '预定发送时间'`);
        await queryRunner.query(`ALTER TABLE \`email_notification_batches\` CHANGE \`completed_at\` \`completed_at\` timestamp NULL COMMENT '批次完成处理时间'`);
        await queryRunner.query(`ALTER TABLE \`email_notification_batches\` CHANGE \`created_at\` \`created_at\` timestamp(6) NOT NULL COMMENT '创建时间' DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`email_notification_batches\` CHANGE \`updated_at\` \`updated_at\` timestamp(6) NOT NULL COMMENT '更新时间' DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`CREATE INDEX \`IDX_aed4b79d60fbc9d43f7e1cdacc\` ON \`sms_templates\` (\`user_id\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_cec3b2031dfa2a8fac79f614b3\` ON \`sms_received_messages\` (\`sms_provider_id\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_a3336b8b0121a59b254f9e8b07\` ON \`sms_received_messages\` (\`sender_number\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_f3d3bc7afcbbdc2618fb014fe7\` ON \`sms_received_messages\` (\`recipient_number\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_46ff03fd4130f865b19dd17115\` ON \`sms_received_messages\` (\`received_at\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_0a92a44b3493464526a87f1e22\` ON \`sms_messages\` (\`dispatch_batch_id\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_c5ca8873c57083a5de85571761\` ON \`sms_messages\` (\`status\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_e20af7ff56dfe1c582b79d93b6\` ON \`sms_dispatch_batches\` (\`user_id\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_bbe7369988a9a82ef650b5f6f5\` ON \`sms_dispatch_batches\` (\`status\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_acb3d7e5778197a1b4b53af433\` ON \`sms_messages\` (\`provider_id\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`uk_sm_provider_msgid\` ON \`sms_messages\` (\`provider_id\`, \`provider_msgid\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_427785468fb7d2733f59e7d7d3\` ON \`payments\` (\`user_id\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_32b41cdb985a296213e9a928b5\` ON \`payments\` (\`status\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_513421601bd786a33c5a7238f4\` ON \`email_templates\` (\`user_id\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_38c39d8c5ff64c1e08f50b37ee\` ON \`email_received_messages\` (\`in_reply_to_header\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_07b76f7520f321f68bd7c2ceb3\` ON \`email_received_messages\` (\`sender_email\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_f14ac86d71645455ce96f66509\` ON \`email_received_messages\` (\`recipient_email\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_3c80749f5740ed81a460a82481\` ON \`email_received_messages\` (\`received_at\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_0453215c2b0716c04e20d96e70\` ON \`email_received_messages\` (\`type\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_71e3eda7c4f6f8aabc04ddf6a5\` ON \`email_messages\` (\`batch_id\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_e9d7accec169af0bf645f318b8\` ON \`email_messages\` (\`status\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_9f4e430c1c80093618e4ee92f6\` ON \`email_notification_batches\` (\`user_id\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_ac9f76352644690608b020e443\` ON \`email_notification_batches\` (\`email_template_id\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_f5585d60cf221ae9e8c86e4204\` ON \`email_notification_batches\` (\`status\`)`);
        await queryRunner.query(`ALTER TABLE \`accounts\` ADD CONSTRAINT \`FK_3000dad1da61b29953f07476324\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`sms_templates\` ADD CONSTRAINT \`FK_aed4b79d60fbc9d43f7e1cdacca\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`sms_received_messages\` ADD CONSTRAINT \`FK_cec3b2031dfa2a8fac79f614b3c\` FOREIGN KEY (\`sms_provider_id\`) REFERENCES \`sms_providers\`(\`id\`) ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`sms_messages\` ADD CONSTRAINT \`FK_0a92a44b3493464526a87f1e227\` FOREIGN KEY (\`dispatch_batch_id\`) REFERENCES \`sms_dispatch_batches\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`sms_messages\` ADD CONSTRAINT \`FK_acb3d7e5778197a1b4b53af433d\` FOREIGN KEY (\`provider_id\`) REFERENCES \`sms_providers\`(\`id\`) ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`sms_dispatch_batches\` ADD CONSTRAINT \`FK_e20af7ff56dfe1c582b79d93b6c\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`sms_dispatch_batches\` ADD CONSTRAINT \`FK_159cfc63429b190e3d985539ef9\` FOREIGN KEY (\`template_id\`) REFERENCES \`sms_templates\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`payments\` ADD CONSTRAINT \`FK_427785468fb7d2733f59e7d7d39\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`email_templates\` ADD CONSTRAINT \`FK_513421601bd786a33c5a7238f45\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`email_messages\` ADD CONSTRAINT \`FK_71e3eda7c4f6f8aabc04ddf6a54\` FOREIGN KEY (\`batch_id\`) REFERENCES \`email_notification_batches\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`email_notification_batches\` ADD CONSTRAINT \`FK_9f4e430c1c80093618e4ee92f66\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`email_notification_batches\` ADD CONSTRAINT \`FK_ac9f76352644690608b020e443c\` FOREIGN KEY (\`email_template_id\`) REFERENCES \`email_templates\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`email_notification_batches\` DROP FOREIGN KEY \`FK_ac9f76352644690608b020e443c\``);
        await queryRunner.query(`ALTER TABLE \`email_notification_batches\` DROP FOREIGN KEY \`FK_9f4e430c1c80093618e4ee92f66\``);
        await queryRunner.query(`ALTER TABLE \`email_messages\` DROP FOREIGN KEY \`FK_71e3eda7c4f6f8aabc04ddf6a54\``);
        await queryRunner.query(`ALTER TABLE \`email_templates\` DROP FOREIGN KEY \`FK_513421601bd786a33c5a7238f45\``);
        await queryRunner.query(`ALTER TABLE \`payments\` DROP FOREIGN KEY \`FK_427785468fb7d2733f59e7d7d39\``);
        await queryRunner.query(`ALTER TABLE \`sms_dispatch_batches\` DROP FOREIGN KEY \`FK_159cfc63429b190e3d985539ef9\``);
        await queryRunner.query(`ALTER TABLE \`sms_dispatch_batches\` DROP FOREIGN KEY \`FK_e20af7ff56dfe1c582b79d93b6c\``);
        await queryRunner.query(`ALTER TABLE \`sms_messages\` DROP FOREIGN KEY \`FK_acb3d7e5778197a1b4b53af433d\``);
        await queryRunner.query(`ALTER TABLE \`sms_messages\` DROP FOREIGN KEY \`FK_0a92a44b3493464526a87f1e227\``);
        await queryRunner.query(`ALTER TABLE \`sms_received_messages\` DROP FOREIGN KEY \`FK_cec3b2031dfa2a8fac79f614b3c\``);
        await queryRunner.query(`ALTER TABLE \`sms_templates\` DROP FOREIGN KEY \`FK_aed4b79d60fbc9d43f7e1cdacca\``);
        await queryRunner.query(`ALTER TABLE \`accounts\` DROP FOREIGN KEY \`FK_3000dad1da61b29953f07476324\``);
        await queryRunner.query(`DROP INDEX \`IDX_f5585d60cf221ae9e8c86e4204\` ON \`email_notification_batches\``);
        await queryRunner.query(`DROP INDEX \`IDX_ac9f76352644690608b020e443\` ON \`email_notification_batches\``);
        await queryRunner.query(`DROP INDEX \`IDX_9f4e430c1c80093618e4ee92f6\` ON \`email_notification_batches\``);
        await queryRunner.query(`DROP INDEX \`IDX_e9d7accec169af0bf645f318b8\` ON \`email_messages\``);
        await queryRunner.query(`DROP INDEX \`IDX_71e3eda7c4f6f8aabc04ddf6a5\` ON \`email_messages\``);
        await queryRunner.query(`DROP INDEX \`IDX_0453215c2b0716c04e20d96e70\` ON \`email_received_messages\``);
        await queryRunner.query(`DROP INDEX \`IDX_3c80749f5740ed81a460a82481\` ON \`email_received_messages\``);
        await queryRunner.query(`DROP INDEX \`IDX_f14ac86d71645455ce96f66509\` ON \`email_received_messages\``);
        await queryRunner.query(`DROP INDEX \`IDX_07b76f7520f321f68bd7c2ceb3\` ON \`email_received_messages\``);
        await queryRunner.query(`DROP INDEX \`IDX_38c39d8c5ff64c1e08f50b37ee\` ON \`email_received_messages\``);
        await queryRunner.query(`DROP INDEX \`IDX_513421601bd786a33c5a7238f4\` ON \`email_templates\``);
        await queryRunner.query(`DROP INDEX \`IDX_32b41cdb985a296213e9a928b5\` ON \`payments\``);
        await queryRunner.query(`DROP INDEX \`IDX_427785468fb7d2733f59e7d7d3\` ON \`payments\``);
        await queryRunner.query(`DROP INDEX \`uk_sm_provider_msgid\` ON \`sms_messages\``);
        await queryRunner.query(`DROP INDEX \`IDX_acb3d7e5778197a1b4b53af433\` ON \`sms_messages\``);
        await queryRunner.query(`DROP INDEX \`IDX_bbe7369988a9a82ef650b5f6f5\` ON \`sms_dispatch_batches\``);
        await queryRunner.query(`DROP INDEX \`IDX_e20af7ff56dfe1c582b79d93b6\` ON \`sms_dispatch_batches\``);
        await queryRunner.query(`DROP INDEX \`IDX_c5ca8873c57083a5de85571761\` ON \`sms_messages\``);
        await queryRunner.query(`DROP INDEX \`IDX_0a92a44b3493464526a87f1e22\` ON \`sms_messages\``);
        await queryRunner.query(`DROP INDEX \`IDX_46ff03fd4130f865b19dd17115\` ON \`sms_received_messages\``);
        await queryRunner.query(`DROP INDEX \`IDX_f3d3bc7afcbbdc2618fb014fe7\` ON \`sms_received_messages\``);
        await queryRunner.query(`DROP INDEX \`IDX_a3336b8b0121a59b254f9e8b07\` ON \`sms_received_messages\``);
        await queryRunner.query(`DROP INDEX \`IDX_cec3b2031dfa2a8fac79f614b3\` ON \`sms_received_messages\``);
        await queryRunner.query(`DROP INDEX \`IDX_aed4b79d60fbc9d43f7e1cdacc\` ON \`sms_templates\``);
        await queryRunner.query(`ALTER TABLE \`email_notification_batches\` CHANGE \`updated_at\` \`updated_at\` timestamp(0) NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`email_notification_batches\` CHANGE \`created_at\` \`created_at\` timestamp(0) NOT NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`email_notification_batches\` CHANGE \`completed_at\` \`completed_at\` timestamp NULL`);
        await queryRunner.query(`ALTER TABLE \`email_notification_batches\` CHANGE \`scheduled_at\` \`scheduled_at\` timestamp NULL`);
        await queryRunner.query(`ALTER TABLE \`email_notification_batches\` CHANGE \`status\` \`status\` enum COLLATE "utf8mb4_unicode_ci" ('pending', 'processing', 'partially_completed', 'completed', 'failed') NOT NULL DEFAULT 'pending'`);
        await queryRunner.query(`ALTER TABLE \`email_notification_batches\` CHANGE \`failed_count\` \`failed_count\` int UNSIGNED NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE \`email_notification_batches\` CHANGE \`sent_count\` \`sent_count\` int UNSIGNED NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE \`email_notification_batches\` CHANGE \`processed_count\` \`processed_count\` int UNSIGNED NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE \`email_notification_batches\` CHANGE \`total_recipients\` \`total_recipients\` int UNSIGNED NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`email_notification_batches\` CHANGE \`body_text\` \`body_text\` text COLLATE "utf8mb4_unicode_ci" NULL`);
        await queryRunner.query(`ALTER TABLE \`email_notification_batches\` DROP COLUMN \`body_html\``);
        await queryRunner.query(`ALTER TABLE \`email_notification_batches\` ADD \`body_html\` text COLLATE "utf8mb4_unicode_ci" NULL`);
        await queryRunner.query(`ALTER TABLE \`email_notification_batches\` CHANGE \`subject\` \`subject\` varchar(255) COLLATE "utf8mb4_unicode_ci" NULL`);
        await queryRunner.query(`ALTER TABLE \`email_notification_batches\` CHANGE \`email_template_id\` \`email_template_id\` int UNSIGNED NULL`);
        await queryRunner.query(`ALTER TABLE \`email_notification_batches\` CHANGE \`user_id\` \`user_id\` int UNSIGNED NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`email_notification_batches\` ADD CONSTRAINT \`FK_ac9f76352644690608b020e443c\` FOREIGN KEY (\`email_template_id\`) REFERENCES \`email_templates\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`email_notification_batches\` ADD CONSTRAINT \`FK_9f4e430c1c80093618e4ee92f66\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`email_messages\` CHANGE \`updated_at\` \`updated_at\` timestamp(0) NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`email_messages\` CHANGE \`created_at\` \`created_at\` timestamp(0) NOT NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`email_messages\` CHANGE \`status_updated_at\` \`status_updated_at\` timestamp NULL`);
        await queryRunner.query(`ALTER TABLE \`email_messages\` CHANGE \`sent_at\` \`sent_at\` timestamp NULL`);
        await queryRunner.query(`ALTER TABLE \`email_messages\` CHANGE \`error_message\` \`error_message\` text COLLATE "utf8mb4_unicode_ci" NULL`);
        await queryRunner.query(`ALTER TABLE \`email_messages\` DROP INDEX \`IDX_eabe2566f0aa286b2ccad53896\``);
        await queryRunner.query(`ALTER TABLE \`email_messages\` CHANGE \`provider_message_id\` \`provider_message_id\` varchar(255) COLLATE "utf8mb4_unicode_ci" NULL`);
        await queryRunner.query(`ALTER TABLE \`email_messages\` CHANGE \`status\` \`status\` varchar(50) COLLATE "utf8mb4_unicode_ci" NOT NULL DEFAULT 'pending'`);
        await queryRunner.query(`ALTER TABLE \`email_messages\` CHANGE \`recipient_email\` \`recipient_email\` varchar(255) COLLATE "utf8mb4_unicode_ci" NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`email_messages\` CHANGE \`batch_id\` \`batch_id\` bigint UNSIGNED NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`email_messages\` ADD CONSTRAINT \`FK_71e3eda7c4f6f8aabc04ddf6a54\` FOREIGN KEY (\`batch_id\`) REFERENCES \`email_notification_batches\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`email_received_messages\` CHANGE \`created_at\` \`created_at\` timestamp(0) NOT NULL COMMENT 'è®°å½•åˆ›å»ºæ—¶é—´' DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`email_received_messages\` CHANGE \`type\` \`type\` enum COLLATE "utf8mb4_unicode_ci" ('inbound', 'bounce', 'reply', 'complaint') NOT NULL COMMENT 'é‚®ä»¶ç±»åž‹' DEFAULT 'inbound'`);
        await queryRunner.query(`ALTER TABLE \`email_received_messages\` CHANGE \`received_at\` \`received_at\` timestamp NOT NULL COMMENT 'æŽ¥æ”¶æ—¶é—´'`);
        await queryRunner.query(`ALTER TABLE \`email_received_messages\` CHANGE \`body_text\` \`body_text\` mediumtext COLLATE "utf8mb4_unicode_ci" NULL COMMENT 'çº¯æ–‡æœ¬æ­£æ–‡'`);
        await queryRunner.query(`ALTER TABLE \`email_received_messages\` CHANGE \`body_html\` \`body_html\` mediumtext COLLATE "utf8mb4_unicode_ci" NULL COMMENT 'HTML æ­£æ–‡'`);
        await queryRunner.query(`ALTER TABLE \`email_received_messages\` CHANGE \`subject\` \`subject\` varchar(500) COLLATE "utf8mb4_unicode_ci" NULL COMMENT 'é‚®ä»¶ä¸»é¢˜'`);
        await queryRunner.query(`ALTER TABLE \`email_received_messages\` CHANGE \`recipient_email\` \`recipient_email\` varchar(255) COLLATE "utf8mb4_unicode_ci" NOT NULL COMMENT 'æŽ¥æ”¶è€…é‚®ç®± (æœ¬å¹³å°é‚®ç®±)'`);
        await queryRunner.query(`ALTER TABLE \`email_received_messages\` CHANGE \`sender_email\` \`sender_email\` varchar(255) COLLATE "utf8mb4_unicode_ci" NOT NULL COMMENT 'å‘é€è€…é‚®ç®±'`);
        await queryRunner.query(`ALTER TABLE \`email_received_messages\` CHANGE \`in_reply_to_header\` \`in_reply_to_header\` varchar(255) COLLATE "utf8mb4_unicode_ci" NULL COMMENT 'é‚®ä»¶çš„ In-Reply-To header'`);
        await queryRunner.query(`ALTER TABLE \`email_received_messages\` DROP INDEX \`IDX_d4ea1ecd6fed315ed1bdd41bd0\``);
        await queryRunner.query(`ALTER TABLE \`email_received_messages\` CHANGE \`message_id_header\` \`message_id_header\` varchar(255) COLLATE "utf8mb4_unicode_ci" NULL COMMENT 'é‚®ä»¶çš„ Message-ID header'`);
        await queryRunner.query(`ALTER TABLE \`email_templates\` CHANGE \`updated_at\` \`updated_at\` timestamp(0) NOT NULL COMMENT 'æ›´æ–°æ—¶é—´' DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`email_templates\` CHANGE \`created_at\` \`created_at\` timestamp(0) NOT NULL COMMENT 'åˆ›å»ºæ—¶é—´' DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`email_templates\` CHANGE \`variables\` \`variables\` json NULL COMMENT 'æ¨¡æ¿ä¸­ä½¿ç”¨çš„å˜é‡åˆ—è¡¨ (e.g., ["link", "productName"])'`);
        await queryRunner.query(`ALTER TABLE \`email_templates\` CHANGE \`body_text\` \`body_text\` text COLLATE "utf8mb4_unicode_ci" NULL COMMENT 'çº¯æ–‡æœ¬æ ¼å¼é‚®ä»¶æ­£æ–‡æ¨¡æ¿'`);
        await queryRunner.query(`ALTER TABLE \`email_templates\` CHANGE \`body_html\` \`body_html\` text COLLATE "utf8mb4_unicode_ci" NULL COMMENT 'HTML æ ¼å¼é‚®ä»¶æ­£æ–‡æ¨¡æ¿'`);
        await queryRunner.query(`ALTER TABLE \`email_templates\` CHANGE \`subject\` \`subject\` varchar(255) COLLATE "utf8mb4_unicode_ci" NOT NULL COMMENT 'é‚®ä»¶ä¸»é¢˜æ¨¡æ¿'`);
        await queryRunner.query(`ALTER TABLE \`email_templates\` CHANGE \`name\` \`name\` varchar(150) COLLATE "utf8mb4_unicode_ci" NOT NULL COMMENT 'æ¨¡æ¿åç§°'`);
        await queryRunner.query(`ALTER TABLE \`email_templates\` CHANGE \`user_id\` \`user_id\` int UNSIGNED NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`email_templates\` ADD CONSTRAINT \`FK_513421601bd786a33c5a7238f45\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`payments\` CHANGE \`updated_at\` \`updated_at\` timestamp(0) NOT NULL COMMENT 'æ›´æ–°æ—¶é—´' DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`payments\` CHANGE \`created_at\` \`created_at\` timestamp(0) NOT NULL COMMENT 'åˆ›å»ºæ—¶é—´' DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`payments\` CHANGE \`payment_method\` \`payment_method\` varchar(50) COLLATE "utf8mb4_unicode_ci" NULL COMMENT 'æ”¯ä»˜æ–¹å¼'`);
        await queryRunner.query(`ALTER TABLE \`payments\` DROP INDEX \`IDX_3c324ca49dabde7ffc0ef64675\``);
        await queryRunner.query(`ALTER TABLE \`payments\` CHANGE \`transaction_id\` \`transaction_id\` varchar(255) COLLATE "utf8mb4_unicode_ci" NULL COMMENT 'å¤–éƒ¨æ”¯ä»˜ç½‘å…³äº¤æ˜“ID'`);
        await queryRunner.query(`ALTER TABLE \`payments\` CHANGE \`status\` \`status\` enum COLLATE "utf8mb4_unicode_ci" ('pending', 'completed', 'failed') NOT NULL COMMENT 'æ”¯ä»˜çŠ¶æ€' DEFAULT 'pending'`);
        await queryRunner.query(`ALTER TABLE \`payments\` CHANGE \`amount\` \`amount\` decimal(10,2) NOT NULL COMMENT 'å……å€¼é‡‘é¢'`);
        await queryRunner.query(`ALTER TABLE \`payments\` CHANGE \`user_id\` \`user_id\` int UNSIGNED NOT NULL COMMENT 'å…³è”ç”¨æˆ·ID'`);
        await queryRunner.query(`ALTER TABLE \`payments\` ADD CONSTRAINT \`FK_427785468fb7d2733f59e7d7d39\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`sms_messages\` CHANGE \`updated_at\` \`updated_at\` timestamp(0) NOT NULL COMMENT 'è®°å½•æ›´æ–°æ—¶é—´' DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`sms_messages\` CHANGE \`created_at\` \`created_at\` timestamp(0) NOT NULL COMMENT 'è®°å½•åˆ›å»ºæ—¶é—´' DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`sms_messages\` CHANGE \`last_status_check_at\` \`last_status_check_at\` timestamp NULL COMMENT 'æœ€åŽä¸€æ¬¡ä¸»åŠ¨æŸ¥è¯¢çŠ¶æ€çš„æ—¶é—´'`);
        await queryRunner.query(`ALTER TABLE \`sms_messages\` CHANGE \`provider_reported_at\` \`provider_reported_at\` timestamp NULL COMMENT 'æœåŠ¡å•†æŠ¥å‘Šçš„å‘é€/é€è¾¾æ—¶é—´'`);
        await queryRunner.query(`ALTER TABLE \`sms_messages\` CHANGE \`submitted_at\` \`submitted_at\` timestamp NULL COMMENT 'æˆåŠŸæäº¤ç»™æœåŠ¡å•†çš„æ—¶é—´'`);
        await queryRunner.query(`ALTER TABLE \`sms_messages\` CHANGE \`error_message\` \`error_message\` text COLLATE "utf8mb4_unicode_ci" NULL COMMENT 'å‘é€å¤±è´¥æˆ–çŠ¶æ€æŸ¥è¯¢æ—¶çš„é”™è¯¯ä¿¡æ¯'`);
        await queryRunner.query(`ALTER TABLE \`sms_messages\` CHANGE \`provider_status_code\` \`provider_status_code\` varchar(100) COLLATE "utf8mb4_unicode_ci" NULL COMMENT 'æœåŠ¡å•†è¿”å›žçš„åŽŸå§‹çŠ¶æ€ç æˆ–æè¿°'`);
        await queryRunner.query(`ALTER TABLE \`sms_messages\` CHANGE \`status\` \`status\` enum COLLATE "utf8mb4_unicode_ci" ('pending', 'queued', 'submitted', 'sent', 'delivered', 'failed', 'rejected', 'unknown') NOT NULL COMMENT 'æ ‡å‡†åŒ–çš„çŸ­ä¿¡çŠ¶æ€' DEFAULT 'pending'`);
        await queryRunner.query(`ALTER TABLE \`sms_messages\` CHANGE \`provider_orderid\` \`provider_orderid\` varchar(255) COLLATE "utf8mb4_unicode_ci" NULL COMMENT 'å‘é€æ—¶ä¼ é€’ç»™æœåŠ¡å•†çš„è‡ªå®šä¹‰ID (å¦‚æžœæ”¯æŒï¼Œä¾‹å¦‚ç”¨æœ¬è¡¨id)'`);
        await queryRunner.query(`ALTER TABLE \`sms_messages\` CHANGE \`provider_msgid\` \`provider_msgid\` varchar(255) COLLATE "utf8mb4_unicode_ci" NULL COMMENT 'æœåŠ¡å•†è¿”å›žçš„æ¶ˆæ¯ID'`);
        await queryRunner.query(`ALTER TABLE \`sms_messages\` CHANGE \`provider_id\` \`provider_id\` int UNSIGNED NOT NULL COMMENT 'æœ€ç»ˆé€‰æ‹©çš„çŸ­ä¿¡æœåŠ¡å•†ID'`);
        await queryRunner.query(`ALTER TABLE \`sms_messages\` CHANGE \`recipient_number\` \`recipient_number\` varchar(50) COLLATE "utf8mb4_unicode_ci" NOT NULL COMMENT 'æŽ¥æ”¶è€…æ‰‹æœºå·'`);
        await queryRunner.query(`ALTER TABLE \`sms_messages\` CHANGE \`dispatch_batch_id\` \`dispatch_batch_id\` bigint UNSIGNED NOT NULL COMMENT 'å…³è”çš„ç”¨æˆ·è¯·æ±‚æ‰¹æ¬¡ID'`);
        await queryRunner.query(`ALTER TABLE \`sms_messages\` CHANGE \`id\` \`id\` bigint UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'ç³»ç»Ÿå†…éƒ¨å”¯ä¸€æ¶ˆæ¯ID'`);
        await queryRunner.query(`ALTER TABLE \`sms_dispatch_batches\` CHANGE \`updated_at\` \`updated_at\` timestamp(0) NOT NULL COMMENT 'æ›´æ–°æ—¶é—´' DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`sms_dispatch_batches\` CHANGE \`created_at\` \`created_at\` timestamp(0) NOT NULL COMMENT 'åˆ›å»ºæ—¶é—´' DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`sms_dispatch_batches\` CHANGE \`completed_at\` \`completed_at\` timestamp NULL COMMENT 'æ‰¹æ¬¡å®Œæˆå¤„ç†æ—¶é—´'`);
        await queryRunner.query(`ALTER TABLE \`sms_dispatch_batches\` CHANGE \`processing_started_at\` \`processing_started_at\` timestamp NULL COMMENT 'å¼€å§‹å¤„ç†æ—¶é—´'`);
        await queryRunner.query(`ALTER TABLE \`sms_dispatch_batches\` CHANGE \`scheduled_at\` \`scheduled_at\` timestamp NULL COMMENT 'é¢„å®šå‘é€æ—¶é—´'`);
        await queryRunner.query(`ALTER TABLE \`sms_dispatch_batches\` CHANGE \`status\` \`status\` enum COLLATE "utf8mb4_unicode_ci" ('pending', 'processing', 'partially_completed', 'completed', 'failed') NOT NULL COMMENT 'æ‰¹æ¬¡æ•´ä½“å¤„ç†çŠ¶æ€' DEFAULT 'pending'`);
        await queryRunner.query(`ALTER TABLE \`sms_dispatch_batches\` CHANGE \`recipient_count\` \`recipient_count\` int UNSIGNED NOT NULL COMMENT 'è¯·æ±‚ä¸­çš„æŽ¥æ”¶è€…æ•°é‡'`);
        await queryRunner.query(`ALTER TABLE \`sms_dispatch_batches\` CHANGE \`recipients\` \`recipients\` json NOT NULL COMMENT 'ç”¨æˆ·è¯·æ±‚çš„æŽ¥æ”¶è€…å·ç åˆ—è¡¨ (JSON Array of strings)'`);
        await queryRunner.query(`ALTER TABLE \`sms_dispatch_batches\` CHANGE \`content\` \`content\` text COLLATE "utf8mb4_unicode_ci" NOT NULL COMMENT 'è¦å‘é€çš„çŸ­ä¿¡å†…å®¹ (ç›´æŽ¥å†…å®¹æˆ–æ¸²æŸ“åŽçš„æ¨¡æ¿å†…å®¹)'`);
        await queryRunner.query(`ALTER TABLE \`sms_dispatch_batches\` CHANGE \`template_id\` \`template_id\` int UNSIGNED NULL COMMENT 'ä½¿ç”¨çš„çŸ­ä¿¡æ¨¡æ¿ID (å¦‚æžœä½¿ç”¨)'`);
        await queryRunner.query(`ALTER TABLE \`sms_dispatch_batches\` DROP INDEX \`IDX_39a1276cb4b18c33358ead18aa\``);
        await queryRunner.query(`ALTER TABLE \`sms_dispatch_batches\` CHANGE \`request_id\` \`request_id\` varchar(64) COLLATE "utf8mb4_unicode_ci" NULL COMMENT 'å¯é€‰çš„ã€ç”¨æˆ·ä¼ å…¥çš„å”¯ä¸€è¯·æ±‚IDï¼Œç”¨äºŽå¹‚ç­‰æ€§æŽ§åˆ¶'`);
        await queryRunner.query(`ALTER TABLE \`sms_dispatch_batches\` CHANGE \`user_id\` \`user_id\` int UNSIGNED NOT NULL COMMENT 'å‘èµ·è¯·æ±‚çš„ç”¨æˆ·ID'`);
        await queryRunner.query(`ALTER TABLE \`sms_dispatch_batches\` CHANGE \`updated_at\` \`updated_at\` timestamp(0) NOT NULL COMMENT 'æ›´æ–°æ—¶é—´' DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`sms_dispatch_batches\` CHANGE \`created_at\` \`created_at\` timestamp(0) NOT NULL COMMENT 'åˆ›å»ºæ—¶é—´' DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`sms_dispatch_batches\` CHANGE \`completed_at\` \`completed_at\` timestamp NULL COMMENT 'æ‰¹æ¬¡å®Œæˆå¤„ç†æ—¶é—´'`);
        await queryRunner.query(`ALTER TABLE \`sms_dispatch_batches\` CHANGE \`processing_started_at\` \`processing_started_at\` timestamp NULL COMMENT 'å¼€å§‹å¤„ç†æ—¶é—´'`);
        await queryRunner.query(`ALTER TABLE \`sms_dispatch_batches\` CHANGE \`scheduled_at\` \`scheduled_at\` timestamp NULL COMMENT 'é¢„å®šå‘é€æ—¶é—´'`);
        await queryRunner.query(`ALTER TABLE \`sms_dispatch_batches\` CHANGE \`recipient_count\` \`recipient_count\` int UNSIGNED NOT NULL COMMENT 'è¯·æ±‚ä¸­çš„æŽ¥æ”¶è€…æ•°é‡'`);
        await queryRunner.query(`ALTER TABLE \`sms_dispatch_batches\` CHANGE \`recipients\` \`recipients\` json NOT NULL COMMENT 'ç”¨æˆ·è¯·æ±‚çš„æŽ¥æ”¶è€…å·ç åˆ—è¡¨ (JSON Array of strings)'`);
        await queryRunner.query(`ALTER TABLE \`sms_dispatch_batches\` CHANGE \`content\` \`content\` text COLLATE "utf8mb4_unicode_ci" NOT NULL COMMENT 'è¦å‘é€çš„çŸ­ä¿¡å†…å®¹ (ç›´æŽ¥å†…å®¹æˆ–æ¸²æŸ“åŽçš„æ¨¡æ¿å†…å®¹)'`);
        await queryRunner.query(`ALTER TABLE \`sms_dispatch_batches\` CHANGE \`template_id\` \`template_id\` int UNSIGNED NULL COMMENT 'ä½¿ç”¨çš„çŸ­ä¿¡æ¨¡æ¿ID (å¦‚æžœä½¿ç”¨)'`);
        await queryRunner.query(`ALTER TABLE \`sms_dispatch_batches\` CHANGE \`status\` \`status\` enum COLLATE "utf8mb4_unicode_ci" ('pending', 'processing', 'partially_completed', 'completed', 'failed') NOT NULL COMMENT 'æ‰¹æ¬¡æ•´ä½“å¤„ç†çŠ¶æ€' DEFAULT 'pending'`);
        await queryRunner.query(`ALTER TABLE \`sms_dispatch_batches\` DROP INDEX \`IDX_39a1276cb4b18c33358ead18aa\``);
        await queryRunner.query(`ALTER TABLE \`sms_dispatch_batches\` CHANGE \`request_id\` \`request_id\` varchar(64) COLLATE "utf8mb4_unicode_ci" NULL COMMENT 'å¯é€‰çš„ã€ç”¨æˆ·ä¼ å…¥çš„å”¯ä¸€è¯·æ±‚IDï¼Œç”¨äºŽå¹‚ç­‰æ€§æŽ§åˆ¶'`);
        await queryRunner.query(`ALTER TABLE \`sms_dispatch_batches\` CHANGE \`user_id\` \`user_id\` int UNSIGNED NOT NULL COMMENT 'å‘èµ·è¯·æ±‚çš„ç”¨æˆ·ID'`);
        await queryRunner.query(`ALTER TABLE \`sms_messages\` CHANGE \`updated_at\` \`updated_at\` timestamp(0) NOT NULL COMMENT 'è®°å½•æ›´æ–°æ—¶é—´' DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`sms_messages\` CHANGE \`created_at\` \`created_at\` timestamp(0) NOT NULL COMMENT 'è®°å½•åˆ›å»ºæ—¶é—´' DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`sms_messages\` CHANGE \`last_status_check_at\` \`last_status_check_at\` timestamp NULL COMMENT 'æœ€åŽä¸€æ¬¡ä¸»åŠ¨æŸ¥è¯¢çŠ¶æ€çš„æ—¶é—´'`);
        await queryRunner.query(`ALTER TABLE \`sms_messages\` CHANGE \`provider_reported_at\` \`provider_reported_at\` timestamp NULL COMMENT 'æœåŠ¡å•†æŠ¥å‘Šçš„å‘é€/é€è¾¾æ—¶é—´'`);
        await queryRunner.query(`ALTER TABLE \`sms_messages\` CHANGE \`submitted_at\` \`submitted_at\` timestamp NULL COMMENT 'æˆåŠŸæäº¤ç»™æœåŠ¡å•†çš„æ—¶é—´'`);
        await queryRunner.query(`ALTER TABLE \`sms_messages\` CHANGE \`error_message\` \`error_message\` text COLLATE "utf8mb4_unicode_ci" NULL COMMENT 'å‘é€å¤±è´¥æˆ–çŠ¶æ€æŸ¥è¯¢æ—¶çš„é”™è¯¯ä¿¡æ¯'`);
        await queryRunner.query(`ALTER TABLE \`sms_messages\` CHANGE \`provider_status_code\` \`provider_status_code\` varchar(100) COLLATE "utf8mb4_unicode_ci" NULL COMMENT 'æœåŠ¡å•†è¿”å›žçš„åŽŸå§‹çŠ¶æ€ç æˆ–æè¿°'`);
        await queryRunner.query(`ALTER TABLE \`sms_messages\` CHANGE \`provider_orderid\` \`provider_orderid\` varchar(255) COLLATE "utf8mb4_unicode_ci" NULL COMMENT 'å‘é€æ—¶ä¼ é€’ç»™æœåŠ¡å•†çš„è‡ªå®šä¹‰ID (å¦‚æžœæ”¯æŒï¼Œä¾‹å¦‚ç”¨æœ¬è¡¨id)'`);
        await queryRunner.query(`ALTER TABLE \`sms_messages\` DROP INDEX \`IDX_1c352885b3a00833386c570d2b\``);
        await queryRunner.query(`ALTER TABLE \`sms_messages\` CHANGE \`provider_msgid\` \`provider_msgid\` varchar(255) COLLATE "utf8mb4_unicode_ci" NULL COMMENT 'æœåŠ¡å•†è¿”å›žçš„æ¶ˆæ¯ID'`);
        await queryRunner.query(`ALTER TABLE \`sms_messages\` CHANGE \`status\` \`status\` enum COLLATE "utf8mb4_unicode_ci" ('pending', 'queued', 'submitted', 'sent', 'delivered', 'failed', 'rejected', 'unknown') NOT NULL COMMENT 'æ ‡å‡†åŒ–çš„çŸ­ä¿¡çŠ¶æ€' DEFAULT 'pending'`);
        await queryRunner.query(`ALTER TABLE \`sms_messages\` CHANGE \`recipient_number\` \`recipient_number\` varchar(50) COLLATE "utf8mb4_unicode_ci" NOT NULL COMMENT 'æŽ¥æ”¶è€…æ‰‹æœºå·'`);
        await queryRunner.query(`ALTER TABLE \`sms_messages\` CHANGE \`provider_id\` \`provider_id\` int UNSIGNED NOT NULL COMMENT 'æœ€ç»ˆé€‰æ‹©çš„çŸ­ä¿¡æœåŠ¡å•†ID'`);
        await queryRunner.query(`ALTER TABLE \`sms_messages\` CHANGE \`dispatch_batch_id\` \`dispatch_batch_id\` bigint UNSIGNED NOT NULL COMMENT 'å…³è”çš„ç”¨æˆ·è¯·æ±‚æ‰¹æ¬¡ID'`);
        await queryRunner.query(`ALTER TABLE \`sms_messages\` CHANGE \`id\` \`id\` bigint UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'ç³»ç»Ÿå†…éƒ¨å”¯ä¸€æ¶ˆæ¯ID'`);
        await queryRunner.query(`ALTER TABLE \`sms_received_messages\` CHANGE \`created_at\` \`created_at\` timestamp(0) NOT NULL COMMENT 'è®°å½•åˆ›å»ºæ—¶é—´' DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`sms_received_messages\` CHANGE \`received_at\` \`received_at\` timestamp NOT NULL COMMENT 'æŽ¥æ”¶æ—¶é—´ (ç”±æœåŠ¡å•†æä¾›æˆ–å›žè°ƒæ—¶é—´)'`);
        await queryRunner.query(`ALTER TABLE \`sms_received_messages\` CHANGE \`content\` \`content\` text COLLATE "utf8mb4_unicode_ci" NOT NULL COMMENT 'çŸ­ä¿¡å†…å®¹'`);
        await queryRunner.query(`ALTER TABLE \`sms_received_messages\` CHANGE \`recipient_number\` \`recipient_number\` varchar(50) COLLATE "utf8mb4_unicode_ci" NOT NULL COMMENT 'æŽ¥æ”¶è€…å·ç  (æœ¬å¹³å°å·ç )'`);
        await queryRunner.query(`ALTER TABLE \`sms_received_messages\` CHANGE \`sender_number\` \`sender_number\` varchar(50) COLLATE "utf8mb4_unicode_ci" NOT NULL COMMENT 'å‘é€è€…æ‰‹æœºå·'`);
        await queryRunner.query(`ALTER TABLE \`sms_received_messages\` DROP INDEX \`IDX_66be7944e1306a00f04c8951b6\``);
        await queryRunner.query(`ALTER TABLE \`sms_received_messages\` CHANGE \`provider_message_id\` \`provider_message_id\` varchar(255) COLLATE "utf8mb4_unicode_ci" NULL COMMENT 'æœåŠ¡å•†çš„æ¶ˆæ¯ID'`);
        await queryRunner.query(`ALTER TABLE \`sms_received_messages\` CHANGE \`sms_provider_id\` \`sms_provider_id\` int UNSIGNED NOT NULL COMMENT 'æŽ¥æ”¶æ¶ˆæ¯çš„æœåŠ¡å•†ID'`);
        await queryRunner.query(`ALTER TABLE \`sms_providers\` CHANGE \`updated_at\` \`updated_at\` timestamp(0) NOT NULL COMMENT 'æ›´æ–°æ—¶é—´' DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`sms_providers\` CHANGE \`created_at\` \`created_at\` timestamp(0) NOT NULL COMMENT 'åˆ›å»ºæ—¶é—´' DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`sms_providers\` CHANGE \`is_active\` \`is_active\` tinyint(1) NOT NULL COMMENT 'æ˜¯å¦å¯ç”¨' DEFAULT '1'`);
        await queryRunner.query(`ALTER TABLE \`sms_providers\` CHANGE \`config_details\` \`config_details\` json NULL COMMENT 'ç‰¹å®šæä¾›å•†çš„é¢å¤–é…ç½® (JSONæ ¼å¼, e.g., onbuka appid)'`);
        await queryRunner.query(`ALTER TABLE \`sms_providers\` CHANGE \`base_url\` \`base_url\` varchar(255) COLLATE "utf8mb4_unicode_ci" NULL COMMENT 'API åŸºç¡€ URL'`);
        await queryRunner.query(`ALTER TABLE \`sms_providers\` CHANGE \`api_secret\` \`api_secret\` varchar(255) COLLATE "utf8mb4_unicode_ci" NULL COMMENT 'API Secret'`);
        await queryRunner.query(`ALTER TABLE \`sms_providers\` CHANGE \`api_key\` \`api_key\` varchar(255) COLLATE "utf8mb4_unicode_ci" NULL COMMENT 'API Key'`);
        await queryRunner.query(`ALTER TABLE \`sms_providers\` CHANGE \`display_name\` \`display_name\` varchar(150) COLLATE "utf8mb4_unicode_ci" NULL COMMENT 'æä¾›å•†æ˜¾ç¤ºåç§°'`);
        await queryRunner.query(`ALTER TABLE \`sms_providers\` DROP INDEX \`IDX_543d375bc13c040df4c53f23ac\``);
        await queryRunner.query(`ALTER TABLE \`sms_providers\` CHANGE \`name\` \`name\` varchar(100) COLLATE "utf8mb4_unicode_ci" NOT NULL COMMENT 'æä¾›å•†å”¯ä¸€æ ‡è¯†åç§° (e.g., onbuka, aliyun)'`);
        await queryRunner.query(`ALTER TABLE \`sms_templates\` CHANGE \`updated_at\` \`updated_at\` timestamp(0) NOT NULL COMMENT 'æ›´æ–°æ—¶é—´' DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`sms_templates\` CHANGE \`created_at\` \`created_at\` timestamp(0) NOT NULL COMMENT 'åˆ›å»ºæ—¶é—´' DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`sms_templates\` CHANGE \`variables\` \`variables\` json NULL COMMENT 'æ¨¡æ¿ä¸­ä½¿ç”¨çš„å˜é‡åˆ—è¡¨ (e.g., ["code", "userName"])'`);
        await queryRunner.query(`ALTER TABLE \`sms_templates\` DROP COLUMN \`provider_template_id\``);
        await queryRunner.query(`ALTER TABLE \`sms_templates\` ADD \`provider_template_id\` varchar(100) COLLATE "utf8mb4_unicode_ci" NULL COMMENT 'åœ¨æœåŠ¡å•†å¹³å°çš„æ¨¡æ¿ID (å¯é€‰)'`);
        await queryRunner.query(`ALTER TABLE \`sms_templates\` CHANGE \`content\` \`content\` text COLLATE "utf8mb4_unicode_ci" NOT NULL COMMENT 'çŸ­ä¿¡æ¨¡æ¿å†…å®¹'`);
        await queryRunner.query(`ALTER TABLE \`sms_templates\` DROP INDEX \`IDX_d9bd873bf52604c57cdcec10b4\``);
        await queryRunner.query(`ALTER TABLE \`sms_templates\` DROP COLUMN \`name\``);
        await queryRunner.query(`ALTER TABLE \`sms_templates\` ADD \`name\` varchar(150) COLLATE "utf8mb4_unicode_ci" NOT NULL COMMENT 'æ¨¡æ¿åç§°'`);
        await queryRunner.query(`ALTER TABLE \`sms_templates\` CHANGE \`user_id\` \`user_id\` int UNSIGNED NOT NULL COMMENT 'åˆ›å»ºæ¨¡æ¿çš„ç”¨æˆ·ID'`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`updated_at\` \`updated_at\` timestamp(0) NOT NULL COMMENT 'æ›´æ–°æ—¶é—´' DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`created_at\` \`created_at\` timestamp(0) NOT NULL COMMENT 'åˆ›å»ºæ—¶é—´' DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`is_active\` \`is_active\` tinyint(1) NOT NULL COMMENT 'è´¦æˆ·æ˜¯å¦æ¿€æ´»' DEFAULT '1'`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`role\` \`role\` enum COLLATE "utf8mb4_unicode_ci" ('admin', 'user') NOT NULL COMMENT 'ç”¨æˆ·è§’è‰²' DEFAULT 'user'`);
        await queryRunner.query(`ALTER TABLE \`users\` DROP INDEX \`IDX_97672ac88f789774dd47f7c8be\``);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`email\` \`email\` varchar(255) COLLATE "utf8mb4_unicode_ci" NOT NULL COMMENT 'é‚®ç®±åœ°å€'`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`password_hash\` \`password_hash\` varchar(255) COLLATE "utf8mb4_unicode_ci" NOT NULL COMMENT 'å“ˆå¸ŒåŠ å¯†åŽçš„å¯†ç '`);
        await queryRunner.query(`ALTER TABLE \`users\` DROP INDEX \`IDX_fe0bb3f6520ee0469504521e71\``);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`username\` \`username\` varchar(100) COLLATE "utf8mb4_unicode_ci" NOT NULL COMMENT 'ç”¨æˆ·å'`);
        await queryRunner.query(`ALTER TABLE \`accounts\` CHANGE \`updated_at\` \`updated_at\` timestamp(0) NOT NULL COMMENT 'æ›´æ–°æ—¶é—´' DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`accounts\` CHANGE \`created_at\` \`created_at\` timestamp(0) NOT NULL COMMENT 'åˆ›å»ºæ—¶é—´' DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`accounts\` CHANGE \`balance\` \`balance\` decimal(12,4) NOT NULL COMMENT 'è´¦æˆ·ä½™é¢' DEFAULT '0.0000'`);
        await queryRunner.query(`ALTER TABLE \`accounts\` DROP INDEX \`IDX_3000dad1da61b29953f0747632\``);
        await queryRunner.query(`ALTER TABLE \`accounts\` CHANGE \`user_id\` \`user_id\` int UNSIGNED NOT NULL COMMENT 'å…³è”ç”¨æˆ·ID'`);
        await queryRunner.query(`ALTER TABLE \`accounts\` CHANGE \`id\` \`id\` int UNSIGNED NOT NULL AUTO_INCREMENT`);
        await queryRunner.query(`ALTER TABLE \`accounts\` ADD CONSTRAINT \`FK_3000dad1da61b29953f07476324\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`sms_dispatch_batches\` DROP COLUMN \`processing_completed_at\``);
        await queryRunner.query(`ALTER TABLE \`sms_dispatch_batches\` DROP COLUMN \`failure_count\``);
        await queryRunner.query(`ALTER TABLE \`sms_dispatch_batches\` DROP COLUMN \`success_count\``);
        await queryRunner.query(`ALTER TABLE \`sms_dispatch_batches\` DROP COLUMN \`processed_count\``);
        await queryRunner.query(`ALTER TABLE \`sms_dispatch_batches\` DROP COLUMN \`direct_content\``);
        await queryRunner.query(`ALTER TABLE \`sms_dispatch_batches\` DROP COLUMN \`content_type\``);
        await queryRunner.query(`ALTER TABLE \`email_notification_batches\` COMMENT 'é‚®ä»¶æŽ¨é€æ‰¹æ¬¡ä¿¡æ¯'`);
        await queryRunner.query(`ALTER TABLE \`email_messages\` COMMENT 'å•æ¡é‚®ä»¶å‘é€è¯¦æƒ…ä¸ŽçŠ¶æ€'`);
        await queryRunner.query(`ALTER TABLE \`email_received_messages\` COMMENT 'æŽ¥æ”¶åˆ°çš„é‚®ä»¶è®°å½•'`);
        await queryRunner.query(`ALTER TABLE \`email_templates\` COMMENT 'é‚®ä»¶æ¨¡æ¿è¡¨'`);
        await queryRunner.query(`ALTER TABLE \`payments\` COMMENT 'æ”¯ä»˜å’Œå……å€¼è®°å½•è¡¨'`);
        await queryRunner.query(`ALTER TABLE \`sms_messages\` COMMENT 'å•æ¡çŸ­ä¿¡å‘é€è¯¦æƒ…ä¸ŽçŠ¶æ€'`);
        await queryRunner.query(`ALTER TABLE \`sms_dispatch_batches\` COMMENT 'çŸ­ä¿¡è°ƒåº¦æ‰¹æ¬¡ (ç”¨æˆ·è¯·æ±‚)'`);
        await queryRunner.query(`ALTER TABLE \`sms_dispatch_batches\` COMMENT 'çŸ­ä¿¡è°ƒåº¦æ‰¹æ¬¡ (ç”¨æˆ·è¯·æ±‚)'`);
        await queryRunner.query(`ALTER TABLE \`sms_messages\` COMMENT 'å•æ¡çŸ­ä¿¡å‘é€è¯¦æƒ…ä¸ŽçŠ¶æ€'`);
        await queryRunner.query(`ALTER TABLE \`sms_received_messages\` COMMENT 'æŽ¥æ”¶åˆ°çš„çŸ­ä¿¡è®°å½• (ä¸Šè¡Œ)'`);
        await queryRunner.query(`ALTER TABLE \`sms_providers\` COMMENT 'çŸ­ä¿¡æœåŠ¡æä¾›å•†é…ç½®'`);
        await queryRunner.query(`ALTER TABLE \`sms_templates\` COMMENT 'çŸ­ä¿¡æ¨¡æ¿è¡¨'`);
        await queryRunner.query(`ALTER TABLE \`users\` COMMENT 'ç”¨æˆ·ä¿¡æ¯è¡¨'`);
        await queryRunner.query(`ALTER TABLE \`accounts\` COMMENT 'ç”¨æˆ·è´¦æˆ·ä½™é¢è¡¨'`);
        await queryRunner.query(`CREATE INDEX \`idx_email_batches_user_id\` ON \`email_notification_batches\` (\`user_id\`)`);
        await queryRunner.query(`CREATE INDEX \`idx_email_batches_status\` ON \`email_notification_batches\` (\`status\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`provider_message_id\` ON \`email_messages\` (\`provider_message_id\`)`);
        await queryRunner.query(`CREATE INDEX \`idx_email_messages_status\` ON \`email_messages\` (\`status\`)`);
        await queryRunner.query(`CREATE INDEX \`idx_email_messages_batch_id\` ON \`email_messages\` (\`batch_id\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`message_id_header\` ON \`email_received_messages\` (\`message_id_header\`)`);
        await queryRunner.query(`CREATE INDEX \`idx_email_received_type\` ON \`email_received_messages\` (\`type\`)`);
        await queryRunner.query(`CREATE INDEX \`idx_email_received_sender\` ON \`email_received_messages\` (\`sender_email\`)`);
        await queryRunner.query(`CREATE INDEX \`idx_email_received_recipient\` ON \`email_received_messages\` (\`recipient_email\`)`);
        await queryRunner.query(`CREATE INDEX \`idx_email_received_at\` ON \`email_received_messages\` (\`received_at\`)`);
        await queryRunner.query(`CREATE INDEX \`idx_email_templates_user_id\` ON \`email_templates\` (\`user_id\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`transaction_id\` ON \`payments\` (\`transaction_id\`)`);
        await queryRunner.query(`CREATE INDEX \`idx_payments_user_id\` ON \`payments\` (\`user_id\`)`);
        await queryRunner.query(`CREATE INDEX \`idx_payments_status\` ON \`payments\` (\`status\`)`);
        await queryRunner.query(`CREATE INDEX \`template_id\` ON \`sms_dispatch_batches\` (\`template_id\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`request_id\` ON \`sms_dispatch_batches\` (\`request_id\`)`);
        await queryRunner.query(`CREATE INDEX \`idx_sdb_user_id\` ON \`sms_dispatch_batches\` (\`user_id\`)`);
        await queryRunner.query(`CREATE INDEX \`idx_sdb_status\` ON \`sms_dispatch_batches\` (\`status\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`uk_sm_provider_msgid\` ON \`sms_messages\` (\`provider_id\`, \`provider_msgid\`)`);
        await queryRunner.query(`CREATE INDEX \`idx_sm_status\` ON \`sms_messages\` (\`status\`)`);
        await queryRunner.query(`CREATE INDEX \`idx_sm_recipient_number\` ON \`sms_messages\` (\`recipient_number\`)`);
        await queryRunner.query(`CREATE INDEX \`idx_sm_provider_msgid\` ON \`sms_messages\` (\`provider_msgid\`)`);
        await queryRunner.query(`CREATE INDEX \`idx_sm_provider_id_status\` ON \`sms_messages\` (\`provider_id\`, \`status\`)`);
        await queryRunner.query(`CREATE INDEX \`idx_sm_dispatch_batch_id\` ON \`sms_messages\` (\`dispatch_batch_id\`)`);
        await queryRunner.query(`CREATE INDEX \`sms_provider_id\` ON \`sms_received_messages\` (\`sms_provider_id\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`provider_message_id\` ON \`sms_received_messages\` (\`provider_message_id\`)`);
        await queryRunner.query(`CREATE INDEX \`idx_sms_received_sender\` ON \`sms_received_messages\` (\`sender_number\`)`);
        await queryRunner.query(`CREATE INDEX \`idx_sms_received_recipient\` ON \`sms_received_messages\` (\`recipient_number\`)`);
        await queryRunner.query(`CREATE INDEX \`idx_sms_received_at\` ON \`sms_received_messages\` (\`received_at\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`name\` ON \`sms_providers\` (\`name\`)`);
        await queryRunner.query(`CREATE INDEX \`idx_sms_templates_user_id\` ON \`sms_templates\` (\`user_id\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`username\` ON \`users\` (\`username\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`email\` ON \`users\` (\`email\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`user_id\` ON \`accounts\` (\`user_id\`)`);
        await queryRunner.query(`ALTER TABLE \`email_notification_batches\` ADD CONSTRAINT \`email_notification_batches_ibfk_2\` FOREIGN KEY (\`email_template_id\`) REFERENCES \`email_templates\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`email_notification_batches\` ADD CONSTRAINT \`email_notification_batches_ibfk_1\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`email_messages\` ADD CONSTRAINT \`email_messages_ibfk_1\` FOREIGN KEY (\`batch_id\`) REFERENCES \`email_notification_batches\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`email_templates\` ADD CONSTRAINT \`email_templates_ibfk_1\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`payments\` ADD CONSTRAINT \`payments_ibfk_1\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`sms_dispatch_batches\` ADD CONSTRAINT \`sms_dispatch_batches_ibfk_2\` FOREIGN KEY (\`template_id\`) REFERENCES \`sms_templates\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`sms_dispatch_batches\` ADD CONSTRAINT \`sms_dispatch_batches_ibfk_1\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`sms_messages\` ADD CONSTRAINT \`sms_messages_ibfk_2\` FOREIGN KEY (\`provider_id\`) REFERENCES \`sms_providers\`(\`id\`) ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`sms_messages\` ADD CONSTRAINT \`sms_messages_ibfk_1\` FOREIGN KEY (\`dispatch_batch_id\`) REFERENCES \`sms_dispatch_batches\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`sms_received_messages\` ADD CONSTRAINT \`sms_received_messages_ibfk_1\` FOREIGN KEY (\`sms_provider_id\`) REFERENCES \`sms_providers\`(\`id\`) ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`sms_templates\` ADD CONSTRAINT \`sms_templates_ibfk_1\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`accounts\` ADD CONSTRAINT \`accounts_ibfk_1\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

}
