version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: sms-serve-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: sms_serve
      MYSQL_ROOT_HOST: '%'
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
      - ./docker/mysql/mysql.cnf:/etc/mysql/conf.d/mysql.cnf
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    networks:
      - sms-serve-net

  redis:
    image: redis:7
    container_name: sms-serve-redis
    restart: always
    ports:
      - '6380:6379'
    volumes:
      - redis_data:/data
    networks:
      - sms-serve-net

volumes:
  mysql_data:
  redis_data:

networks:
  sms-serve-net:
    driver: bridge
